Gridded Probabilities
NCAR/HWT_mode pull request #11
Opened 2021-08-26 23:37 UTC by charlie-becker

- Add functions to calculate gridded probabilities instead of object probs (Supports WRF and HRRR)
-  Add plot function for plotting neighborhood probabilities
- Change distance metric to use a projection instead of lat / lon
- Fix bug introduced with new pandas / numpy version when setting integer values to type 'float'

2021-08-30 14:58 UTC, djgagne requested changes
I have a couple of suggestions in the comments for making installation and CI easier plus addressing a potential map projection issue when calculating distances.

2021-08-30 14:58 UTC, djgagne commented on .travis.yml
> +  - conda create -n test --yes -c conda-forge python=$PYTHON_VERSION pip numpy scipy matplotlib pandas xarray pyyaml netcdf4 scikit-learn seaborn cartopy tqdm memory_profiler scikit-image pyarrow s3f
Can you create an environment.yml file for the repo and edit the travis.yml file to install everything from the environment.yml file?

2021-08-30 14:58 UTC, djgagne commented on hwtmode/data.py
> +            scale_values.loc[var_name, "max"] = patch_data[..., v].max().values
Wrap the min and max calls with `float(patch_data[...)` to ensure a single floating point value is returned rather than a data array. In the initial setup of scale_values = pd.DataFrame, initialize it with 0.0 instead of 0 to ensure all the values are floats rather than ints.

2021-08-30 14:58 UTC, djgagne commented on hwtmode/evaluation.py
> +            obs_indx = find_coord_indices(lon_to_web_mercator(ds['lon'].values),
If you're calculating distances between points, web mercator is not an appropriate projection because it does not preserve distances well. Lambert conformal conic works better on the US scale assuming you place your center lat and lon over the central US. The impact is probably not very large on the gridding of storm reports, but it could make a difference.

2021-08-30 14:58 UTC, djgagne commented on hwtmode/evaluation.py
> +            obs_indx = find_coord_indices(lon_to_web_mercator(ds['lon'].values),
Use pyproj to do the projection calculation really fast.

2021-08-31 15:48 UTC, charlie-becker commented
All requested changes have been made.

2021-08-31 15:58 UTC, djgagne approved these changes

2021-08-31 15:59 UTC, djgagne commented
The changes look good to me. Merging.

2021-08-31 15:59 UTC, merged