Change case runs, memory profiler, and masked inputs
NCAR/HWT_mode pull request #6
Opened 2020-12-17 19:28 UTC by ggantos

2020-12-17 19:58 UTC, ggantos commented on hwtmode/data.py
> +                     patch_radius=None, mask=False) -> tuple:
look here for changes to data.py for the boolean flag for masking inputs

2020-12-17 19:58 UTC, ggantos commented on hwtmode/data.py
> +            if mask:
masking in the load_patch_files function, before scaling occurs.

2020-12-17 19:58 UTC, ggantos commented on train_mode_cnn.py
> +                                                                 config["mask"])
This may not be necessary here long-term. I'm not sure if there's a better way to code for this option.

2020-12-17 19:58 UTC, ggantos commented on config/ws_mode_cnn_train_201014_hm.yml
> +data_path: "/glade/scratch/dgagne/NSC_data/track_data_nsc_3km_REFL_COM_ws_nc"
I added a bunch of config files for the various test cases I ran, starting with this one.

2020-12-21 21:21 UTC, charlie-becker commented on train_mode_cnn.py
> +                                                                 config["mask"])
Seems like a reasonable way to add the option, however, perhaps you could update all the config files to have this parameter so they wouldn't fail?  Which maybe leads to a broader question... which (or how many) config files should we track in git?

2020-12-21 21:41 UTC, charlie-becker approved these changes
Looks good. See minor comments and potential suggestions.

2020-12-21 21:41 UTC, charlie-becker commented on cheyenne_train_script.sh
> +#PBS -l select=1:mem=109GB
I'm not too familiar with PBS / Cheyenne. Why 109GB? what does the 1:mem mean?

2020-12-21 21:41 UTC, charlie-becker commented on config/ws_mode_cnn_train_small.yml
> +mask: False
Should we add this to every config file so they do not fail when run?

2020-12-21 21:41 UTC, charlie-becker commented on train_mode_cnn.py
> +                                                                 config["mask"])
Seems like a reasonable way to add the option, but would require all config files to be updated. Which maybe leads to a broader question... which (or how many) config files should we track in git?

I suppose you could code something like:
if mask exists in config
mask = config['mask']
else mask = None

with corresponding logic in the data_loader function. But that may be too convoluted.

2020-12-21 22:21 UTC, ggantos commented on train_mode_cnn.py
> +                                                                 config["mask"])
I'm not sure how many configs should be saved... I don't think we need all of the ones I added so I'd be happy to remove them now that they're logged in history.

I was wondering about adding something like if mask exists... wasn't sure if this was better or adding a line to config would be more clear. @djgagne perhaps you can let us know what is cleanest and easiest long-term?

2020-12-21 22:26 UTC, ggantos commented on cheyenne_train_script.sh
> +#PBS -l select=1:mem=109GB
When I ran with the previous version, I got an error so my edit was an attempt at fixing that. I believe it did work in the end and if I'm remembering correctly, I asking for 128G of memory was not possible.

2020-12-21 22:26 UTC, ggantos commented on config/ws_mode_cnn_train_small.yml
> +mask: False
I would be happy to do so unless it would be better to add the if exists then logic. Not sure which is cleaner/easier long-term.

2021-01-11 23:00 UTC, djgagne requested changes
The mask experiments will need to be re-run because the storms were masked out instead of the background.

2021-01-11 23:00 UTC, djgagne commented on config/ws_mode_cnn_train_small.yml
> +mask: False
If we determine masking to be a useful thing to do, then make it a required variable. I'd like my other comment to be addressed first before doing that though.

2021-01-14 22:09 UTC, djgagne commented on hwtmode/data.py
> +            if mask:
I was wrong on this. Sorry. Resolving.

2021-01-14 22:12 UTC, ggantos commented on config/ws_mode_cnn_train_small.yml
> +mask: False
Based off of our conversations, I'll make this a non-required variable that defaults to False.

2021-01-19 19:29 UTC, ggantos commented
Hi @djgagne @charlie-becker changes made for PR review. Both scenarios run so should be good to go to close. Thanks!

2021-01-19 20:56 UTC, djgagne approved these changes

2021-01-19 20:56 UTC, djgagne commented
Everything looks good. Merging.

2021-01-19 20:56 UTC, merged